Added search/filter and extra columns to Truck Grid
TAC-Insight/fw-scale-frontend pull request #102
Opened 2023-07-25 20:02 UTC by HaleyBoles

- added quick search
- added hauler and status filter
- added reset filter button
- added driver, license, RFID, truck assignment
- updated UDFs in grid to match Orders grid
- turned off Floating Filter
- added activate/inactivate button to trucks

2023-07-26 17:32 UTC, sspoon865 commented on src/routes/Trucks.tsx
> +						onGridReady={() => {
Autofocus for your Search box doesn't work.

I would probably go back and add an `id="searchInput"` to the Input for search and then use `document.getElementById("searchInput")?.focus();`

This would also allow you to remove lines 80-85 (since they're currently setting focus on the New Truck link)—unless you'd rather it be the opposite, which if so, you could just remove `onGridReady` and keep the autofocus on New Truck link.

2023-07-26 17:34 UTC, sspoon865 commented on src/routes/Trucks.tsx
> +							<Select
Inactive status filter shows no inactive trucks.
This is probably due to Chris's prefilter. There is no inactiveTrucks query like there is for orders. May need to add an issue for it in scale-backend.

2023-07-26 17:34 UTC, sspoon865 commented on src/routes/Trucks.tsx
> +				/**
I think it would be better to remove the pre-check for UDFs on Inactivating a truck. The UDF fields aren't required in a truckEdit mutation, so you can just omit them if there are no UDFs set on the truck. This way a user doesn't have to leave the screen where they're trying to inactivate a truck.

2023-07-26 17:35 UTC, sspoon865 commented on src/routes/Trucks.tsx
> +						onCellKeyDown={async (event) => {
Nice! I need to add this as well to Orders screen so it's not just spacebar that selects crap. Thanks AG Grid. 😔

2023-07-26 17:36 UTC, sspoon865 requested changes
See code comments.

2023-07-26 18:51 UTC, HaleyBoles commented on src/routes/Trucks.tsx
> +						onGridReady={() => {
Ohhh yeah the default autofocus is on the New Truck link. We can switch this to the Search if that makes more sense? Probably should go through and do that on all of the grids.

2023-07-26 18:52 UTC, HaleyBoles commented on src/routes/Trucks.tsx
> +							<Select
Inactive status is bringing in inactive trucks for me? Unless something just changed on the new server version..

2023-07-26 18:52 UTC, HaleyBoles commented on src/routes/Trucks.tsx
> +				/**
If a UDF is required, the truck status change fails since its on TruckEdit mutation. There is not currently a mutation for just changing truck status, but if there was we could remove all that crap

2023-07-26 19:48 UTC, sspoon865 commented on src/routes/Trucks.tsx
> +							<Select
Yes, on the newest server version, no Inactive trucks are showing up. Even when creating a brand new truck, then inactivating it.

2023-07-26 20:02 UTC, HaleyBoles commented on src/routes/Trucks.tsx
> +							<Select
Oh well that explains it... probably want those added back in I would think?

2023-07-26 20:05 UTC, sspoon865 commented on src/routes/Trucks.tsx
> +				/**
This should not be required, check out [#8](https://github.com/TAC-Insight/fw-scale-backend/issues/8). You may need to add another issue for Chris on the scale-backend. He had to change the OrderEditInputType to accept empty values for UDFs (then you could just continue checking for empty values on the edit page).

2023-07-26 20:07 UTC, sspoon865 commented on src/routes/Trucks.tsx
> +							<Select
That or you could possibly not allow for filtering to view inactive ones. 🤷 In the current app, you can't even inactivate a truck anyway.

2023-07-27 19:04 UTC, HaleyBoles commented on src/routes/Trucks.tsx
> +				/**
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/128633188/676b29a1-0574-4bb3-809e-a11b4cfc3d76)
Yeah this is what I get when I comment out all of the UDF logic :(

2023-07-27 19:19 UTC, HaleyBoles commented on src/routes/Trucks.tsx
> +							<Select
https://github.com/TAC-Insight/fw-scale-backend/issues/16

Added issue for this so can update accordingly if they are re-added or not

2023-07-27 19:20 UTC, HaleyBoles commented on src/routes/Trucks.tsx
> +				/**
Will see about creating another issue to add a setTruckStatus mutation (like the setOrderStatus one) if we are going to include inactive trucks in the sync 
https://github.com/TAC-Insight/fw-scale-backend/issues/16

if not, we can remove this button entirely

2023-07-27 19:21 UTC, HaleyBoles commented on src/routes/Trucks.tsx
> +						onGridReady={() => {
Will use new ref on input component from Ticket History PR 
https://github.com/TAC-Insight/fw-scale-frontend/pull/105

2023-07-28 14:14 UTC, HaleyBoles commented on src/routes/Trucks.tsx
> +							<Select
Updated to include prefilter to show inactive trucks: 
https://github.com/TAC-Insight/fw-scale-frontend/pull/102/commits/8574c5b21e61f644729ec228427324ecd7aabc73

2023-07-28 14:15 UTC, HaleyBoles commented on src/routes/Trucks.tsx
> +				/**
Re: https://github.com/TAC-Insight/fw-scale-backend/issues/16

left this in for now, and we can update to new Mutation if/when it is added later on. I can make a project task for this once this is merged

2023-07-28 21:05 UTC, HaleyBoles commented
https://github.com/TAC-Insight/fw-scale-frontend/pull/102/commits/39cb97237588156843f1709fad047ce049754ad4
jk it wasn;t there because I forgot to add it 🤪

2023-07-28 21:14 UTC, sspoon865 approved these changes

2023-07-28 21:15 UTC, merged