58 customer screen
TAC-Insight/fw-scale-frontend pull request #103
Opened 2023-07-26 14:08 UTC by HaleyBoles

- added Customer screen, route, and ctrlSlash
- matched grid and filters to orders/trucks

2023-07-26 18:46 UTC, sspoon865 commented on src/routes/Customers.tsx
> +						onGridReady={() => {
May want to switch to `document.getElementById("<id>")?.focus()` here as well, or remove lines 67-70

2023-07-26 18:47 UTC, sspoon865 requested changes
See code comments.

Will also need to pull from `main` once #102 has been merged.

2023-07-27 19:22 UTC, HaleyBoles commented on src/routes/Customers.tsx
> +						onGridReady={() => {
will use new ref on input component from Ticket History PR
https://github.com/TAC-Insight/fw-scale-frontend/pull/105

2023-07-28 19:45 UTC, sspoon865 approved these changes

2023-07-28 19:45 UTC, merged