104 ticket history screen standardize grid add click to view full ticket details
TAC-Insight/fw-scale-frontend pull request #105
Opened 2023-07-27 17:09 UTC by HaleyBoles

- Added ref to Input component for auto-focus
- Refined filter layout
- Added lane filter
- Removed floating filter from grid
- added a ticket detail pop-up if you click anything other than a button column
- paired down query grid data since there is more in the pop-up
- Updated UDFs in grid data to new method
- Updated cell button renderers to be less cluttered
- Updated to onSelectEvent function for cell buttons
- Moved Void popUp children to function
- Split Void Cell Renderer to its own function
- added unsynced ticket column (only shows if there are unsynced tickets)

2023-07-27 17:10 UTC, HaleyBoles commented
@sspoon865 included fixes discussed in other grid PRs

2023-07-28 15:16 UTC, sspoon865 commented on src/components/Input.tsx
After reviewing... I think it would be best if we chucked out the `inputRef` changes.

It is an unnecessary addition, especially since the Input component already has an `autofocus` property. Should probably just change that elsewhere in Orders/Trucks/etc.

2023-07-28 15:17 UTC, sspoon865 commented on src/routes/TicketHistory.tsx
> +	// Initial load to set focus
This can be removed in favor of `autofocus` on Search

2023-07-28 15:18 UTC, sspoon865 commented on src/routes/TicketHistory.tsx
> +								inputRef={focusSearchRef}
Can be removed in favor of `autofocus`.

```suggestion
								autofocus
```

2023-07-28 15:18 UTC, sspoon865 requested changes
See code comments.

2023-07-28 16:03 UTC, sspoon865 commented on src/routes/TicketHistory.tsx
> +	const [filteredTicketes, setFilteredTickets] = useState<DeviceTicket[]>();
smol spelling error here. Would be good to keep it the same as your state setter function for clarity.

```suggestion
	const [filteredTickets, setFilteredTickets] = useState<DeviceTicket[]>();
```

2023-07-28 16:06 UTC, sspoon865 commented
Also noticed you cannot immediately see the newest tickets created if you:
1. Create new ticket
2. Immediately navigate to History screen

You have to update the lane filters to get the ticket to show up, or refresh the page.

Could potentially fix this by using a `.filter()` function on your ticketData in AG Grid's `rowData` and instead filter by Lane Name there (or in a separate function as you currently have it).

2023-07-28 16:06 UTC, HaleyBoles commented on src/routes/TicketHistory.tsx
> +	const [filteredTicketes, setFilteredTickets] = useState<DeviceTicket[]>();
Ohhh good catch

2023-07-28 16:28 UTC, HaleyBoles commented
> Also noticed you cannot immediately see the newest tickets created if you:
> 
> 1. Create new ticket
> 2. Immediately navigate to History screen
> 
> You have to update the lane filters to get the ticket to show up, or refresh the page.
> 
> Could potentially fix this by using a `.filter()` function on your ticketData in AG Grid's `rowData` and instead filter by Lane Name there (or in a separate function as you currently have it).

Looking into the cause of this? Did the same thing on my end

2023-07-28 19:37 UTC, sspoon865 approved these changes

2023-07-28 19:38 UTC, sspoon865 commented
🥳 Very nice!

2023-07-28 19:38 UTC, merged