279 trucks grid assignment updates && grid search simplification && other grid work
TAC-Insight/fw-scale-frontend pull request #294
Opened 2023-10-04 15:28 UTC by HaleyBoles

- Updated trucks grid assignment to use localAssignedOrderProduct in truck query
- Updated grid searches to component & simplified
   - related cleanup from removing extra fields
- Added getQuickFilterText to any custom formatted/defined grid columns so search field matches displayed field
   - Swapped inYard grid to use quickSearch on grid instead of pre-filter since getQuickFilterText added all options
- Made sure grids have same props and suppression and styling
   - Updated to all use gridOptions
   - added some minWidths and configured width/flex styling
- Added truck details popup from truck grid
- Removed truck status (truckEdit) button and replaced with details button on truck grid
   - This was very broken, commented out for now until we have a proper mutation for it

2023-10-04 17:41 UTC, sspoon865 requested changes
I think shying away from setting hard widths on columns and using more flex columns would be beneficial (since setting a flex width will fill the remaining space of a grid, making sure that on different screen sizes there will be at least one column that fills any remaining spaces to prevent gaps).

Also, minor nitpick and not necessary, but you could switch out your `initialWidth`s to just use `width` since initialWidth is only used when generating a new column on the fly using the grid APIs, otherwise it behaves exactly like width.

2023-10-04 17:41 UTC, sspoon865 commented on src/routes/InYard.tsx
>  			},
The date & time columns are squished:
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/4155618/9cd292df-1c77-42c3-83de-60136827dead)

Would probably be better to leave these as `flex: 1` or `flex: 1.5`

2023-10-04 17:41 UTC, sspoon865 commented on src/routes/InYard.tsx
>  				flex: 1,
Loader column is huge when it's the only `flex` column left:
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/4155618/f89744a0-93e3-424e-8b87-030fa16b2a2d)

2023-10-04 17:41 UTC, sspoon865 commented on src/routes/Requests.tsx
>  						<AgGridReact
Huge blank gap in the request grid:
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/4155618/a30a3bd0-210f-4c0c-8cc0-9cc423ff4c5a)

This grid could also benefit from having a `flex` column or two (probably request info and/or product).

2023-10-04 20:49 UTC, HaleyBoles commented on src/routes/InYard.tsx
>  			},
The problem I have with leaving them all flex is that you can't control the width it uses on load, it just makes them all an approx flex width based on screen size on load so it squishes everything up more-so than defining widths for the important stuff

2023-10-04 20:50 UTC, HaleyBoles commented on src/routes/TicketHistory.tsx
> +						<div className="flex flex-row space-x-2">
I think all of these are from screen res differences 🤔 I can take another pass at sizing

2023-10-04 21:31 UTC, sspoon865 commented on src/routes/InYard.tsx
>  			},
You can still use the minWidth property to set a minimum width (so that more important information doesn't get cut off on smaller screens). Also setting a few of them to use flex will allow them to take up more space on larger screens, however.

I think on columns where you may have additional information that is nice to see, but not necessary, flex columns can be useful (like `ID - Description` type columns, set the minWidth wide enough to see the important `ID` but if it's also flex, it can grow larger to potentially show `- Description` as well).

2023-10-05 13:38 UTC, HaleyBoles commented
Also reduced Ticket History "days" to 7

2023-10-05 13:57 UTC, sspoon865 approved these changes
Nice!! Looks good on smaller and larger screen sizes, and zooming in and out on each.

2023-10-05 13:57 UTC, merged